// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: streamcontrol.proto

package streamcontrol_grpc

import (
	chatwebhook_grpc "github.com/xaionaro-go/chatwebhook/pkg/grpc/protobuf/go/chatwebhook_grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of chat/chatwebhook.proto.

type PlatformID = chatwebhook_grpc.PlatformID

const PlatformID_platformIDUndefined = chatwebhook_grpc.PlatformID_platformIDUndefined
const PlatformID_platformIDKick = chatwebhook_grpc.PlatformID_platformIDKick
const PlatformID_platformIDTwitch = chatwebhook_grpc.PlatformID_platformIDTwitch
const PlatformID_platformIDYouTube = chatwebhook_grpc.PlatformID_platformIDYouTube

var PlatformID_name = chatwebhook_grpc.PlatformID_name
var PlatformID_value = chatwebhook_grpc.PlatformID_value

type PlatformEventType = chatwebhook_grpc.PlatformEventType

const PlatformEventType_platformEventTypeUndefined = chatwebhook_grpc.PlatformEventType_platformEventTypeUndefined
const PlatformEventType_platformEventTypeChatMessage = chatwebhook_grpc.PlatformEventType_platformEventTypeChatMessage
const PlatformEventType_platformEventTypeCheer = chatwebhook_grpc.PlatformEventType_platformEventTypeCheer
const PlatformEventType_platformEventTypeAdBreak = chatwebhook_grpc.PlatformEventType_platformEventTypeAdBreak
const PlatformEventType_platformEventTypeFollow = chatwebhook_grpc.PlatformEventType_platformEventTypeFollow
const PlatformEventType_platformEventTypeStreamOnline = chatwebhook_grpc.PlatformEventType_platformEventTypeStreamOnline
const PlatformEventType_platformEventTypeStreamOffline = chatwebhook_grpc.PlatformEventType_platformEventTypeStreamOffline
const PlatformEventType_platformEventTypeStreamInfoUpdate = chatwebhook_grpc.PlatformEventType_platformEventTypeStreamInfoUpdate
const PlatformEventType_platformEventTypeSubscriptionNew = chatwebhook_grpc.PlatformEventType_platformEventTypeSubscriptionNew
const PlatformEventType_platformEventTypeSubscriptionRenewed = chatwebhook_grpc.PlatformEventType_platformEventTypeSubscriptionRenewed
const PlatformEventType_platformEventTypeGiftedSubscription = chatwebhook_grpc.PlatformEventType_platformEventTypeGiftedSubscription
const PlatformEventType_platformEventTypeRaid = chatwebhook_grpc.PlatformEventType_platformEventTypeRaid
const PlatformEventType_platformEventTypeChannelShoutoutReceive = chatwebhook_grpc.PlatformEventType_platformEventTypeChannelShoutoutReceive
const PlatformEventType_platformEventTypeBan = chatwebhook_grpc.PlatformEventType_platformEventTypeBan
const PlatformEventType_platformEventTypeAutoModHold = chatwebhook_grpc.PlatformEventType_platformEventTypeAutoModHold
const PlatformEventType_platformEventTypeChannelPointRedemption = chatwebhook_grpc.PlatformEventType_platformEventTypeChannelPointRedemption
const PlatformEventType_platformEventTypeChatMessageDeleted = chatwebhook_grpc.PlatformEventType_platformEventTypeChatMessageDeleted
const PlatformEventType_platformEventTypeGreeting PlatformEventType = 1536
const PlatformEventType_platformEventTypeOther = chatwebhook_grpc.PlatformEventType_platformEventTypeOther

var PlatformEventType_name = chatwebhook_grpc.PlatformEventType_name
var PlatformEventType_value = chatwebhook_grpc.PlatformEventType_value

type Currency = chatwebhook_grpc.Currency

const Currency_CURRENCY_UNDEFINED = chatwebhook_grpc.Currency_CURRENCY_UNDEFINED
const Currency_CURRENCY_USD = chatwebhook_grpc.Currency_CURRENCY_USD
const Currency_CURRENCY_EUR = chatwebhook_grpc.Currency_CURRENCY_EUR
const Currency_CURRENCY_GBP = chatwebhook_grpc.Currency_CURRENCY_GBP
const Currency_CURRENCY_JPY = chatwebhook_grpc.Currency_CURRENCY_JPY
const Currency_CURRENCY_TWITCH_BITS = chatwebhook_grpc.Currency_CURRENCY_TWITCH_BITS
const Currency_CURRENCY_OTHER = chatwebhook_grpc.Currency_CURRENCY_OTHER

var Currency_name = chatwebhook_grpc.Currency_name
var Currency_value = chatwebhook_grpc.Currency_value

type TextFormatType = chatwebhook_grpc.TextFormatType

const TextFormatType_TEXT_FORMAT_TYPE_UNDEFINED = chatwebhook_grpc.TextFormatType_TEXT_FORMAT_TYPE_UNDEFINED
const TextFormatType_TEXT_FORMAT_TYPE_PLAIN = chatwebhook_grpc.TextFormatType_TEXT_FORMAT_TYPE_PLAIN
const TextFormatType_TEXT_FORMAT_TYPE_MARKDOWN = chatwebhook_grpc.TextFormatType_TEXT_FORMAT_TYPE_MARKDOWN
const TextFormatType_TEXT_FORMAT_TYPE_HTML = chatwebhook_grpc.TextFormatType_TEXT_FORMAT_TYPE_HTML

var TextFormatType_name = chatwebhook_grpc.TextFormatType_name
var TextFormatType_value = chatwebhook_grpc.TextFormatType_value

type SubscribeRequest = chatwebhook_grpc.SubscribeRequest
type User = chatwebhook_grpc.User
type Money = chatwebhook_grpc.Money
type Message = chatwebhook_grpc.Message
type Event = chatwebhook_grpc.Event

type Placeholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	mi := &file_streamcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_streamcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_streamcontrol_proto_rawDescGZIP(), []int{0}
}

var File_streamcontrol_proto protoreflect.FileDescriptor

const file_streamcontrol_proto_rawDesc = "" +
	"\n" +
	"\x13streamcontrol.proto\x12\rstreamcontrol\x1a\x16chat/chatwebhook.proto\"\r\n" +
	"\vPlaceholderBSZQgithub.com/xaionaro-go/streamctl/pkg/streamcontrol/protobuf/go/streamcontrol_grpcP\x00b\x06proto3"

var (
	file_streamcontrol_proto_rawDescOnce sync.Once
	file_streamcontrol_proto_rawDescData []byte
)

func file_streamcontrol_proto_rawDescGZIP() []byte {
	file_streamcontrol_proto_rawDescOnce.Do(func() {
		file_streamcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamcontrol_proto_rawDesc), len(file_streamcontrol_proto_rawDesc)))
	})
	return file_streamcontrol_proto_rawDescData
}

var file_streamcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_streamcontrol_proto_goTypes = []any{
	(*Placeholder)(nil), // 0: streamcontrol.Placeholder
}
var file_streamcontrol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamcontrol_proto_init() }
func file_streamcontrol_proto_init() {
	if File_streamcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamcontrol_proto_rawDesc), len(file_streamcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streamcontrol_proto_goTypes,
		DependencyIndexes: file_streamcontrol_proto_depIdxs,
		MessageInfos:      file_streamcontrol_proto_msgTypes,
	}.Build()
	File_streamcontrol_proto = out.File
	file_streamcontrol_proto_goTypes = nil
	file_streamcontrol_proto_depIdxs = nil
}
