// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stream_list.proto

package ytgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveChatMessageListRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LiveChatId       string                 `protobuf:"bytes,1,opt,name=live_chat_id,json=liveChatId,proto3" json:"live_chat_id,omitempty"`
	Part             []string               `protobuf:"bytes,2,rep,name=part,proto3" json:"part,omitempty"`
	MaxResults       uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	PageToken        string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ProfileImageSize uint32                 `protobuf:"varint,5,opt,name=profile_image_size,json=profileImageSize,proto3" json:"profile_image_size,omitempty"`
	Hl               string                 `protobuf:"bytes,6,opt,name=hl,proto3" json:"hl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LiveChatMessageListRequest) Reset() {
	*x = LiveChatMessageListRequest{}
	mi := &file_stream_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatMessageListRequest) ProtoMessage() {}

func (x *LiveChatMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatMessageListRequest.ProtoReflect.Descriptor instead.
func (*LiveChatMessageListRequest) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{0}
}

func (x *LiveChatMessageListRequest) GetLiveChatId() string {
	if x != nil {
		return x.LiveChatId
	}
	return ""
}

func (x *LiveChatMessageListRequest) GetPart() []string {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *LiveChatMessageListRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *LiveChatMessageListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *LiveChatMessageListRequest) GetProfileImageSize() uint32 {
	if x != nil {
		return x.ProfileImageSize
	}
	return 0
}

func (x *LiveChatMessageListRequest) GetHl() string {
	if x != nil {
		return x.Hl
	}
	return ""
}

type LiveChatMessageListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Etag           string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	NextPageToken  string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	PageInfo       *PageInfo              `protobuf:"bytes,4,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	Items          []*LiveChatMessage     `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	OfflineAt      string                 `protobuf:"bytes,6,opt,name=offline_at,json=offlineAt,proto3" json:"offline_at,omitempty"`
	ActivePollItem *LiveChatMessage       `protobuf:"bytes,7,opt,name=active_poll_item,json=activePollItem,proto3" json:"active_poll_item,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LiveChatMessageListResponse) Reset() {
	*x = LiveChatMessageListResponse{}
	mi := &file_stream_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatMessageListResponse) ProtoMessage() {}

func (x *LiveChatMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatMessageListResponse.ProtoReflect.Descriptor instead.
func (*LiveChatMessageListResponse) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{1}
}

func (x *LiveChatMessageListResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LiveChatMessageListResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *LiveChatMessageListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *LiveChatMessageListResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *LiveChatMessageListResponse) GetItems() []*LiveChatMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LiveChatMessageListResponse) GetOfflineAt() string {
	if x != nil {
		return x.OfflineAt
	}
	return ""
}

func (x *LiveChatMessageListResponse) GetActivePollItem() *LiveChatMessage {
	if x != nil {
		return x.ActivePollItem
	}
	return nil
}

type PageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalResults   int32                  `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	ResultsPerPage int32                  `protobuf:"varint,2,opt,name=results_per_page,json=resultsPerPage,proto3" json:"results_per_page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_stream_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *PageInfo) GetResultsPerPage() int32 {
	if x != nil {
		return x.ResultsPerPage
	}
	return 0
}

type LiveChatMessage struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Kind          string                        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Etag          string                        `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	Id            string                        `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Snippet       *LiveChatMessageSnippet       `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	AuthorDetails *LiveChatMessageAuthorDetails `protobuf:"bytes,5,opt,name=author_details,json=authorDetails,proto3" json:"author_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveChatMessage) Reset() {
	*x = LiveChatMessage{}
	mi := &file_stream_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatMessage) ProtoMessage() {}

func (x *LiveChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatMessage.ProtoReflect.Descriptor instead.
func (*LiveChatMessage) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{3}
}

func (x *LiveChatMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LiveChatMessage) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *LiveChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveChatMessage) GetSnippet() *LiveChatMessageSnippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

func (x *LiveChatMessage) GetAuthorDetails() *LiveChatMessageAuthorDetails {
	if x != nil {
		return x.AuthorDetails
	}
	return nil
}

type LiveChatMessageSnippet struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Type                string                       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LiveChatId          string                       `protobuf:"bytes,2,opt,name=live_chat_id,json=liveChatId,proto3" json:"live_chat_id,omitempty"`
	AuthorChannelId     string                       `protobuf:"bytes,3,opt,name=author_channel_id,json=authorChannelId,proto3" json:"author_channel_id,omitempty"`
	PublishedAt         string                       `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	HasDisplayContent   bool                         `protobuf:"varint,5,opt,name=has_display_content,json=hasDisplayContent,proto3" json:"has_display_content,omitempty"`
	DisplayMessage      string                       `protobuf:"bytes,6,opt,name=display_message,json=displayMessage,proto3" json:"display_message,omitempty"`
	TextMessageDetails  *LiveChatTextMessageDetails  `protobuf:"bytes,7,opt,name=text_message_details,json=textMessageDetails,proto3" json:"text_message_details,omitempty"`
	SuperChatDetails    *LiveChatSuperChatDetails    `protobuf:"bytes,8,opt,name=super_chat_details,json=superChatDetails,proto3" json:"super_chat_details,omitempty"`
	SuperStickerDetails *LiveChatSuperStickerDetails `protobuf:"bytes,9,opt,name=super_sticker_details,json=superStickerDetails,proto3" json:"super_sticker_details,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LiveChatMessageSnippet) Reset() {
	*x = LiveChatMessageSnippet{}
	mi := &file_stream_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatMessageSnippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatMessageSnippet) ProtoMessage() {}

func (x *LiveChatMessageSnippet) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatMessageSnippet.ProtoReflect.Descriptor instead.
func (*LiveChatMessageSnippet) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{4}
}

func (x *LiveChatMessageSnippet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LiveChatMessageSnippet) GetLiveChatId() string {
	if x != nil {
		return x.LiveChatId
	}
	return ""
}

func (x *LiveChatMessageSnippet) GetAuthorChannelId() string {
	if x != nil {
		return x.AuthorChannelId
	}
	return ""
}

func (x *LiveChatMessageSnippet) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *LiveChatMessageSnippet) GetHasDisplayContent() bool {
	if x != nil {
		return x.HasDisplayContent
	}
	return false
}

func (x *LiveChatMessageSnippet) GetDisplayMessage() string {
	if x != nil {
		return x.DisplayMessage
	}
	return ""
}

func (x *LiveChatMessageSnippet) GetTextMessageDetails() *LiveChatTextMessageDetails {
	if x != nil {
		return x.TextMessageDetails
	}
	return nil
}

func (x *LiveChatMessageSnippet) GetSuperChatDetails() *LiveChatSuperChatDetails {
	if x != nil {
		return x.SuperChatDetails
	}
	return nil
}

func (x *LiveChatMessageSnippet) GetSuperStickerDetails() *LiveChatSuperStickerDetails {
	if x != nil {
		return x.SuperStickerDetails
	}
	return nil
}

type LiveChatTextMessageDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageText   string                 `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveChatTextMessageDetails) Reset() {
	*x = LiveChatTextMessageDetails{}
	mi := &file_stream_list_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatTextMessageDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatTextMessageDetails) ProtoMessage() {}

func (x *LiveChatTextMessageDetails) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatTextMessageDetails.ProtoReflect.Descriptor instead.
func (*LiveChatTextMessageDetails) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{5}
}

func (x *LiveChatTextMessageDetails) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

type LiveChatSuperChatDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AmountMicros        int64                  `protobuf:"varint,1,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	Currency            string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountDisplayString string                 `protobuf:"bytes,3,opt,name=amount_display_string,json=amountDisplayString,proto3" json:"amount_display_string,omitempty"`
	UserComment         string                 `protobuf:"bytes,4,opt,name=user_comment,json=userComment,proto3" json:"user_comment,omitempty"`
	Tier                int32                  `protobuf:"varint,5,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LiveChatSuperChatDetails) Reset() {
	*x = LiveChatSuperChatDetails{}
	mi := &file_stream_list_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatSuperChatDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatSuperChatDetails) ProtoMessage() {}

func (x *LiveChatSuperChatDetails) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatSuperChatDetails.ProtoReflect.Descriptor instead.
func (*LiveChatSuperChatDetails) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{6}
}

func (x *LiveChatSuperChatDetails) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

func (x *LiveChatSuperChatDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LiveChatSuperChatDetails) GetAmountDisplayString() string {
	if x != nil {
		return x.AmountDisplayString
	}
	return ""
}

func (x *LiveChatSuperChatDetails) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *LiveChatSuperChatDetails) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type LiveChatSuperStickerDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AmountMicros        int64                  `protobuf:"varint,1,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	Currency            string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountDisplayString string                 `protobuf:"bytes,3,opt,name=amount_display_string,json=amountDisplayString,proto3" json:"amount_display_string,omitempty"`
	Tier                int32                  `protobuf:"varint,4,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LiveChatSuperStickerDetails) Reset() {
	*x = LiveChatSuperStickerDetails{}
	mi := &file_stream_list_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatSuperStickerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatSuperStickerDetails) ProtoMessage() {}

func (x *LiveChatSuperStickerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatSuperStickerDetails.ProtoReflect.Descriptor instead.
func (*LiveChatSuperStickerDetails) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{7}
}

func (x *LiveChatSuperStickerDetails) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

func (x *LiveChatSuperStickerDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LiveChatSuperStickerDetails) GetAmountDisplayString() string {
	if x != nil {
		return x.AmountDisplayString
	}
	return ""
}

func (x *LiveChatSuperStickerDetails) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type LiveChatMessageAuthorDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId       string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelUrl      string                 `protobuf:"bytes,2,opt,name=channel_url,json=channelUrl,proto3" json:"channel_url,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,4,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	IsVerified      bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsChatOwner     bool                   `protobuf:"varint,6,opt,name=is_chat_owner,json=isChatOwner,proto3" json:"is_chat_owner,omitempty"`
	IsChatSponsor   bool                   `protobuf:"varint,7,opt,name=is_chat_sponsor,json=isChatSponsor,proto3" json:"is_chat_sponsor,omitempty"`
	IsChatModerator bool                   `protobuf:"varint,8,opt,name=is_chat_moderator,json=isChatModerator,proto3" json:"is_chat_moderator,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LiveChatMessageAuthorDetails) Reset() {
	*x = LiveChatMessageAuthorDetails{}
	mi := &file_stream_list_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatMessageAuthorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatMessageAuthorDetails) ProtoMessage() {}

func (x *LiveChatMessageAuthorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_stream_list_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatMessageAuthorDetails.ProtoReflect.Descriptor instead.
func (*LiveChatMessageAuthorDetails) Descriptor() ([]byte, []int) {
	return file_stream_list_proto_rawDescGZIP(), []int{8}
}

func (x *LiveChatMessageAuthorDetails) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *LiveChatMessageAuthorDetails) GetChannelUrl() string {
	if x != nil {
		return x.ChannelUrl
	}
	return ""
}

func (x *LiveChatMessageAuthorDetails) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LiveChatMessageAuthorDetails) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *LiveChatMessageAuthorDetails) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *LiveChatMessageAuthorDetails) GetIsChatOwner() bool {
	if x != nil {
		return x.IsChatOwner
	}
	return false
}

func (x *LiveChatMessageAuthorDetails) GetIsChatSponsor() bool {
	if x != nil {
		return x.IsChatSponsor
	}
	return false
}

func (x *LiveChatMessageAuthorDetails) GetIsChatModerator() bool {
	if x != nil {
		return x.IsChatModerator
	}
	return false
}

var File_stream_list_proto protoreflect.FileDescriptor

const file_stream_list_proto_rawDesc = "" +
	"\n" +
	"\x11stream_list.proto\x12\n" +
	"youtube.v3\"\xd0\x01\n" +
	"\x1aLiveChatMessageListRequest\x12 \n" +
	"\flive_chat_id\x18\x01 \x01(\tR\n" +
	"liveChatId\x12\x12\n" +
	"\x04part\x18\x02 \x03(\tR\x04part\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\rR\n" +
	"maxResults\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12,\n" +
	"\x12profile_image_size\x18\x05 \x01(\rR\x10profileImageSize\x12\x0e\n" +
	"\x02hl\x18\x06 \x01(\tR\x02hl\"\xb9\x02\n" +
	"\x1bLiveChatMessageListResponse\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\x121\n" +
	"\tpage_info\x18\x04 \x01(\v2\x14.youtube.v3.PageInfoR\bpageInfo\x121\n" +
	"\x05items\x18\x05 \x03(\v2\x1b.youtube.v3.LiveChatMessageR\x05items\x12\x1d\n" +
	"\n" +
	"offline_at\x18\x06 \x01(\tR\tofflineAt\x12E\n" +
	"\x10active_poll_item\x18\a \x01(\v2\x1b.youtube.v3.LiveChatMessageR\x0eactivePollItem\"Y\n" +
	"\bPageInfo\x12#\n" +
	"\rtotal_results\x18\x01 \x01(\x05R\ftotalResults\x12(\n" +
	"\x10results_per_page\x18\x02 \x01(\x05R\x0eresultsPerPage\"\xd8\x01\n" +
	"\x0fLiveChatMessage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12<\n" +
	"\asnippet\x18\x04 \x01(\v2\".youtube.v3.LiveChatMessageSnippetR\asnippet\x12O\n" +
	"\x0eauthor_details\x18\x05 \x01(\v2(.youtube.v3.LiveChatMessageAuthorDetailsR\rauthorDetails\"\x81\x04\n" +
	"\x16LiveChatMessageSnippet\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\flive_chat_id\x18\x02 \x01(\tR\n" +
	"liveChatId\x12*\n" +
	"\x11author_channel_id\x18\x03 \x01(\tR\x0fauthorChannelId\x12!\n" +
	"\fpublished_at\x18\x04 \x01(\tR\vpublishedAt\x12.\n" +
	"\x13has_display_content\x18\x05 \x01(\bR\x11hasDisplayContent\x12'\n" +
	"\x0fdisplay_message\x18\x06 \x01(\tR\x0edisplayMessage\x12X\n" +
	"\x14text_message_details\x18\a \x01(\v2&.youtube.v3.LiveChatTextMessageDetailsR\x12textMessageDetails\x12R\n" +
	"\x12super_chat_details\x18\b \x01(\v2$.youtube.v3.LiveChatSuperChatDetailsR\x10superChatDetails\x12[\n" +
	"\x15super_sticker_details\x18\t \x01(\v2'.youtube.v3.LiveChatSuperStickerDetailsR\x13superStickerDetails\"?\n" +
	"\x1aLiveChatTextMessageDetails\x12!\n" +
	"\fmessage_text\x18\x01 \x01(\tR\vmessageText\"\xc6\x01\n" +
	"\x18LiveChatSuperChatDetails\x12#\n" +
	"\ramount_micros\x18\x01 \x01(\x03R\famountMicros\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x122\n" +
	"\x15amount_display_string\x18\x03 \x01(\tR\x13amountDisplayString\x12!\n" +
	"\fuser_comment\x18\x04 \x01(\tR\vuserComment\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\x05R\x04tier\"\xa6\x01\n" +
	"\x1bLiveChatSuperStickerDetails\x12#\n" +
	"\ramount_micros\x18\x01 \x01(\x03R\famountMicros\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x122\n" +
	"\x15amount_display_string\x18\x03 \x01(\tR\x13amountDisplayString\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\x05R\x04tier\"\xc6\x02\n" +
	"\x1cLiveChatMessageAuthorDetails\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vchannel_url\x18\x02 \x01(\tR\n" +
	"channelUrl\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12*\n" +
	"\x11profile_image_url\x18\x04 \x01(\tR\x0fprofileImageUrl\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\x12\"\n" +
	"\ris_chat_owner\x18\x06 \x01(\bR\visChatOwner\x12&\n" +
	"\x0fis_chat_sponsor\x18\a \x01(\bR\risChatSponsor\x12*\n" +
	"\x11is_chat_moderator\x18\b \x01(\bR\x0fisChatModerator2\x81\x01\n" +
	"\x1cV3DataLiveChatMessageService\x12a\n" +
	"\n" +
	"StreamList\x12&.youtube.v3.LiveChatMessageListRequest\x1a'.youtube.v3.LiveChatMessageListResponse\"\x000\x01BOZMgithub.com/xaionaro-go/streamctl/pkg/streamcontrol/youtube/grpc/ytgrpc;ytgrpcb\x06proto3"

var (
	file_stream_list_proto_rawDescOnce sync.Once
	file_stream_list_proto_rawDescData []byte
)

func file_stream_list_proto_rawDescGZIP() []byte {
	file_stream_list_proto_rawDescOnce.Do(func() {
		file_stream_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_list_proto_rawDesc), len(file_stream_list_proto_rawDesc)))
	})
	return file_stream_list_proto_rawDescData
}

var file_stream_list_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_stream_list_proto_goTypes = []any{
	(*LiveChatMessageListRequest)(nil),   // 0: youtube.v3.LiveChatMessageListRequest
	(*LiveChatMessageListResponse)(nil),  // 1: youtube.v3.LiveChatMessageListResponse
	(*PageInfo)(nil),                     // 2: youtube.v3.PageInfo
	(*LiveChatMessage)(nil),              // 3: youtube.v3.LiveChatMessage
	(*LiveChatMessageSnippet)(nil),       // 4: youtube.v3.LiveChatMessageSnippet
	(*LiveChatTextMessageDetails)(nil),   // 5: youtube.v3.LiveChatTextMessageDetails
	(*LiveChatSuperChatDetails)(nil),     // 6: youtube.v3.LiveChatSuperChatDetails
	(*LiveChatSuperStickerDetails)(nil),  // 7: youtube.v3.LiveChatSuperStickerDetails
	(*LiveChatMessageAuthorDetails)(nil), // 8: youtube.v3.LiveChatMessageAuthorDetails
}
var file_stream_list_proto_depIdxs = []int32{
	2, // 0: youtube.v3.LiveChatMessageListResponse.page_info:type_name -> youtube.v3.PageInfo
	3, // 1: youtube.v3.LiveChatMessageListResponse.items:type_name -> youtube.v3.LiveChatMessage
	3, // 2: youtube.v3.LiveChatMessageListResponse.active_poll_item:type_name -> youtube.v3.LiveChatMessage
	4, // 3: youtube.v3.LiveChatMessage.snippet:type_name -> youtube.v3.LiveChatMessageSnippet
	8, // 4: youtube.v3.LiveChatMessage.author_details:type_name -> youtube.v3.LiveChatMessageAuthorDetails
	5, // 5: youtube.v3.LiveChatMessageSnippet.text_message_details:type_name -> youtube.v3.LiveChatTextMessageDetails
	6, // 6: youtube.v3.LiveChatMessageSnippet.super_chat_details:type_name -> youtube.v3.LiveChatSuperChatDetails
	7, // 7: youtube.v3.LiveChatMessageSnippet.super_sticker_details:type_name -> youtube.v3.LiveChatSuperStickerDetails
	0, // 8: youtube.v3.V3DataLiveChatMessageService.StreamList:input_type -> youtube.v3.LiveChatMessageListRequest
	1, // 9: youtube.v3.V3DataLiveChatMessageService.StreamList:output_type -> youtube.v3.LiveChatMessageListResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_stream_list_proto_init() }
func file_stream_list_proto_init() {
	if File_stream_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_list_proto_rawDesc), len(file_stream_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_list_proto_goTypes,
		DependencyIndexes: file_stream_list_proto_depIdxs,
		MessageInfos:      file_stream_list_proto_msgTypes,
	}.Build()
	File_stream_list_proto = out.File
	file_stream_list_proto_goTypes = nil
	file_stream_list_proto_depIdxs = nil
}
