// Command protoc-gen-streamd-shim is a protoc plugin that generates server-proxy
// and client-wrapper boilerplate for streamd RPCs annotated with
// `option (streamd.proxy) = AUTO;`.
//
// Phase 2 ships the working generator: for each AUTO RPC (whose reply matches
// the shape `{ string error = N; <=1 scalar field; }`) the plugin emits a
// server proxy method on type ProxyServer and a client wrapper method on type
// ProxyClient, mirroring the hand-written pattern used by the Translator*
// family in pkg/streamd/server/grpc.go and pkg/streamd/client/client.go.
//
// One *_proxy.pb.go (server side) and one *_client_proxy.pb.go (client side)
// are emitted per input .proto. Files with zero AUTO RPCs still produce both
// stubs (empty bodies) so the build pipeline is exercised end-to-end.
package main

import (
	"fmt"
	"path"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

// proxyOptionFullName is the fully-qualified name of the method option declared
// in pkg/streamd/grpc/streamd_options.proto. The plugin matches on this name
// instead of importing the generated Go type, so it can run before the typed
// extension stub has been built.
const proxyOptionFullName protoreflect.FullName = "streamd.proxy"

// proxyAutoEnumNumber is the numeric value of streamd.ProxyMode.AUTO. Kept in
// sync with streamd_options.proto by hand; mismatch yields zero AUTO RPCs
// detected (safe default — emits empty proxy file).
const proxyAutoEnumNumber protoreflect.EnumNumber = 1

// proxyOptionFieldNumber is the field number of the (streamd.proxy) extension
// on google.protobuf.MethodOptions. Mirrors the `proxy = 60001` declaration in
// streamd_options.proto.
//
// The plugin matches the option by parsing the raw extension bytes off
// MethodOptions instead of going through the typed extension stub: protogen
// builds Method.Desc before the typeRegistry knows about novel extensions, so
// MethodOptions arrives with the option still in the unknown-fields slot.
const proxyOptionFieldNumber protowire.Number = 60001

// errorFieldName is the canonical reply-field name carrying the in-band error
// string for AUTO RPCs. Replies whose error field is named differently are
// rejected at generation time.
const errorFieldName = "error"

func main() {
	opts := protogen.Options{}
	opts.Run(func(plugin *protogen.Plugin) error {
		// Declare support for proto3 `optional` fields so protoc does not
		// reject inputs (like streamd_options.proto) that use them.
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if err := generateFile(plugin, file); err != nil {
				return fmt.Errorf("generate %s: %w", file.Desc.Path(), err)
			}
		}
		return nil
	})
}

// proxyMethod captures the per-RPC data the templates need.
type proxyMethod struct {
	method     *protogen.Method
	scalar     *protogen.Field // non-error reply field; may be nil if reply is {error} only
	errorField *protogen.Field // the `error` reply field
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	autoMethods, err := collectAutoMethods(file)
	if err != nil {
		return err
	}

	dir := path.Dir(file.GeneratedFilenamePrefix)
	base := path.Base(file.GeneratedFilenamePrefix)
	serverFile := path.Join(dir, base+"_proxy.pb.go")
	clientFile := path.Join(dir, base+"_client_proxy.pb.go")

	if err := emitServer(plugin, file, serverFile, autoMethods); err != nil {
		return err
	}
	if err := emitClient(plugin, file, clientFile, autoMethods); err != nil {
		return err
	}
	return nil
}

func emitServer(
	plugin *protogen.Plugin,
	file *protogen.File,
	outName string,
	methods []proxyMethod,
) error {
	g := plugin.NewGeneratedFile(outName, file.GoImportPath)
	g.P("// Code generated by protoc-gen-streamd-shim. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	if len(methods) == 0 {
		g.P("// No RPCs are annotated with option (streamd.proxy) = AUTO; in this file.")
		return nil
	}

	contextPkg := protogen.GoImportPath("context")

	// Backend interface: one method per AUTO RPC, matching the api.StreamD
	// shape for that method (ctx + return scalar + error).
	g.P("// ProxyServerBackend is the subset of api.StreamD methods consumed by")
	g.P("// the AUTO server proxy. Only methods backing AUTO RPCs are listed.")
	g.P("type ProxyServerBackend interface {")
	for _, m := range methods {
		writeBackendMethodSig(g, m, contextPkg)
	}
	g.P("}")
	g.P()

	g.P("// ProxyServer implements the AUTO subset of StreamDServer by delegating")
	g.P("// to a ProxyServerBackend. Embed it in a concrete server type to inherit")
	g.P("// the AUTO RPC handlers.")
	g.P("type ProxyServer struct {")
	g.P("\tUnimplementedStreamDServer")
	g.P("\tBackend ProxyServerBackend")
	g.P("}")
	g.P()

	for _, m := range methods {
		writeServerMethod(g, m, contextPkg)
	}
	return nil
}

func emitClient(
	plugin *protogen.Plugin,
	file *protogen.File,
	outName string,
	methods []proxyMethod,
) error {
	g := plugin.NewGeneratedFile(outName, file.GoImportPath)
	g.P("// Code generated by protoc-gen-streamd-shim. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	if len(methods) == 0 {
		g.P("// No RPCs are annotated with option (streamd.proxy) = AUTO; in this file.")
		return nil
	}

	contextPkg := protogen.GoImportPath("context")
	errorsPkg := protogen.GoImportPath("errors")
	fmtPkg := protogen.GoImportPath("fmt")
	ioPkg := protogen.GoImportPath("io")
	xgrpcPkg := protogen.GoImportPath("github.com/xaionaro-go/xgrpc")

	g.P("// ProxyClientBackend exposes the gRPC plumbing required by AUTO client")
	g.P("// wrappers. *streamd/client.Client satisfies this interface.")
	g.P("type ProxyClientBackend interface {")
	g.P("\tGRPCClient(", g.QualifiedGoIdent(contextPkg.Ident("Context")), ") (StreamDClient, ", g.QualifiedGoIdent(ioPkg.Ident("Closer")), ", error)")
	g.P("\tProcessError(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", err error) error")
	g.P("\tGetCallWrapper() ", g.QualifiedGoIdent(xgrpcPkg.Ident("CallWrapperFunc")))
	g.P("\tGetRetryConfig() ", g.QualifiedGoIdent(xgrpcPkg.Ident("RetryConfig")))
	g.P("}")
	g.P()

	g.P("// ProxyClient is the embeddable client-side counterpart of ProxyServer:")
	g.P("// it provides the AUTO RPC client methods, dispatching through Backend.")
	g.P("type ProxyClient struct {")
	g.P("\tBackend ProxyClientBackend")
	g.P("}")
	g.P()

	for _, m := range methods {
		writeClientMethod(g, m, contextPkg, errorsPkg, fmtPkg, xgrpcPkg)
	}
	return nil
}

func writeBackendMethodSig(g *protogen.GeneratedFile, m proxyMethod, contextPkg protogen.GoImportPath) {
	if m.scalar == nil {
		g.P("\t", m.method.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ") error")
		return
	}
	g.P("\t", m.method.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ") (", scalarGoType(m.scalar), ", error)")
}

func writeServerMethod(g *protogen.GeneratedFile, m proxyMethod, contextPkg protogen.GoImportPath) {
	reqType := m.method.Input.GoIdent.GoName
	replyType := m.method.Output.GoIdent.GoName

	g.P("// ", m.method.GoName, " is generated from option (streamd.proxy) = AUTO; on the")
	g.P("// streamd.StreamD/", m.method.GoName, " RPC. The in-band error string is folded")
	g.P("// onto the reply (Error field); the gRPC error channel is reserved for")
	g.P("// transport-layer failures.")
	g.P("func (s *ProxyServer) ", m.method.GoName, "(")
	g.P("\tctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ",")
	g.P("\treq *", reqType, ",")
	g.P(") (*", replyType, ", error) {")

	if m.scalar == nil {
		g.P("\terr := s.Backend.", m.method.GoName, "(ctx)")
		g.P("\treply := &", replyType, "{}")
	} else {
		g.P("\tval, err := s.Backend.", m.method.GoName, "(ctx)")
		g.P("\treply := &", replyType, "{", m.scalar.GoName, ": val}")
	}
	g.P("\tif err != nil {")
	g.P("\t\treply.", m.errorField.GoName, " = err.Error()")
	g.P("\t}")
	g.P("\treturn reply, nil")
	g.P("}")
	g.P()
}

func writeClientMethod(
	g *protogen.GeneratedFile,
	m proxyMethod,
	contextPkg, errorsPkg, fmtPkg, xgrpcPkg protogen.GoImportPath,
) {
	reqType := m.method.Input.GoIdent.GoName

	g.P("// ", m.method.GoName, " is generated from option (streamd.proxy) = AUTO;")
	g.P("// on the streamd.StreamD/", m.method.GoName, " RPC. Transport errors are")
	g.P("// wrapped with %w; in-band errors are surfaced as errors.New(reply.Error).")
	if m.scalar == nil {
		g.P("func (p *ProxyClient) ", m.method.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ") error {")
	} else {
		g.P("func (p *ProxyClient) ", m.method.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ") (", scalarGoType(m.scalar), ", error) {")
	}

	g.P("\tclient, conn, err := p.Backend.GRPCClient(ctx)")
	if m.scalar == nil {
		g.P("\tif err != nil { return err }")
	} else {
		g.P("\tif err != nil { return ", scalarZeroValue(m.scalar), ", err }")
	}
	g.P("\tdefer conn.Close()")
	g.P("\treply, err := ", g.QualifiedGoIdent(xgrpcPkg.Ident("CallRetryable")), "(ctx, p.Backend, client.", m.method.GoName, ", &", reqType, "{})")
	g.P("\tif err != nil {")
	if m.scalar == nil {
		g.P("\t\treturn ", g.QualifiedGoIdent(fmtPkg.Ident("Errorf")), "(\"unable to call ", m.method.GoName, ": %w\", err)")
	} else {
		g.P("\t\treturn ", scalarZeroValue(m.scalar), ", ", g.QualifiedGoIdent(fmtPkg.Ident("Errorf")), "(\"unable to call ", m.method.GoName, ": %w\", err)")
	}
	g.P("\t}")
	g.P("\tif msg := reply.Get", m.errorField.GoName, "(); msg != \"\" {")
	if m.scalar == nil {
		g.P("\t\treturn ", g.QualifiedGoIdent(errorsPkg.Ident("New")), "(msg)")
	} else {
		g.P("\t\treturn reply.Get", m.scalar.GoName, "(), ", g.QualifiedGoIdent(errorsPkg.Ident("New")), "(msg)")
	}
	g.P("\t}")
	if m.scalar == nil {
		g.P("\treturn nil")
	} else {
		g.P("\treturn reply.Get", m.scalar.GoName, "(), nil")
	}
	g.P("}")
	g.P()
}

func scalarGoType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BytesKind:
		return "[]byte"
	}
	return ""
}

func scalarZeroValue(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BytesKind:
		return "nil"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0"
	}
	return "0"
}

// collectAutoMethods walks every service in file and returns the methods whose
// MethodOptions carry an extension with full name streamd.proxy and integer
// value AUTO. For each such method it validates the reply shape (scalar +
// error string) and request shape (no fields beyond ctx); violations return
// an error so a misannotated proto trips codegen rather than silently emit
// a malformed proxy.
func collectAutoMethods(file *protogen.File) ([]proxyMethod, error) {
	var out []proxyMethod
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if !methodIsAutoProxied(method) {
				continue
			}
			pm, err := classifyMethod(method)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", service.GoName, method.GoName, err)
			}
			out = append(out, pm)
		}
	}
	return out, nil
}

func classifyMethod(method *protogen.Method) (proxyMethod, error) {
	pm := proxyMethod{method: method}

	// AUTO RPCs must take a request with no fields (no api args beyond ctx).
	if len(method.Input.Fields) != 0 {
		return pm, fmt.Errorf("AUTO request %s must have zero fields (Phase 2 limitation; only api(ctx) shape is supported)", method.Input.GoIdent.GoName)
	}

	for _, f := range method.Output.Fields {
		if string(f.Desc.Name()) == errorFieldName {
			if f.Desc.Kind() != protoreflect.StringKind {
				return pm, fmt.Errorf("reply field %q must be string, got %s", errorFieldName, f.Desc.Kind())
			}
			pm.errorField = f
			continue
		}
		if pm.scalar != nil {
			return pm, fmt.Errorf("AUTO reply %s has more than one non-error field (only one scalar allowed)", method.Output.GoIdent.GoName)
		}
		if scalarGoType(f) == "" {
			return pm, fmt.Errorf("AUTO reply %s field %q has unsupported kind %s (only scalar allowed)", method.Output.GoIdent.GoName, f.Desc.Name(), f.Desc.Kind())
		}
		pm.scalar = f
	}
	if pm.errorField == nil {
		return pm, fmt.Errorf("AUTO reply %s must have a string field named %q", method.Output.GoIdent.GoName, errorFieldName)
	}
	return pm, nil
}

func methodIsAutoProxied(method *protogen.Method) bool {
	options := method.Desc.Options()
	if options == nil {
		return false
	}
	// Fast path: the extension was registered in protoregistry.GlobalTypes (e.g.
	// because streamd_options.pb.go is linked into the plugin in some future
	// build), so RangeExtensions sees it as a typed extension.
	if msg, ok := options.(proto.Message); ok {
		matched := false
		proto.RangeExtensions(msg, func(xt protoreflect.ExtensionType, v any) bool {
			if xt.TypeDescriptor().FullName() != proxyOptionFullName {
				return true
			}
			matched = enumNumberFromExtensionValue(v) == proxyAutoEnumNumber
			return false
		})
		if matched {
			return true
		}
	}
	// Slow path: protogen builds Method.Desc before its dynamic extension
	// registry is populated, so the option arrives in the unknown-fields slot.
	// We parse those bytes ourselves and look for a varint at the proxy field
	// number whose value equals AUTO.
	unknown := options.ProtoReflect().GetUnknown()
	return scanUnknownForAutoProxy(unknown)
}

func enumNumberFromExtensionValue(v any) protoreflect.EnumNumber {
	switch value := v.(type) {
	case protoreflect.EnumNumber:
		return value
	case int32:
		return protoreflect.EnumNumber(value)
	}
	return -1
}

// scanUnknownForAutoProxy walks raw protobuf wire bytes (MethodOptions unknown
// fields) and reports whether a varint at field number proxyOptionFieldNumber
// carries the AUTO enum value. Other tags are skipped via protowire.ConsumeField.
func scanUnknownForAutoProxy(buf []byte) bool {
	for len(buf) > 0 {
		num, typ, n := protowire.ConsumeTag(buf)
		if n < 0 {
			return false
		}
		buf = buf[n:]
		if num == proxyOptionFieldNumber && typ == protowire.VarintType {
			val, vn := protowire.ConsumeVarint(buf)
			if vn < 0 {
				return false
			}
			if protoreflect.EnumNumber(val) == proxyAutoEnumNumber {
				return true
			}
			buf = buf[vn:]
			continue
		}
		skipN := protowire.ConsumeFieldValue(num, typ, buf)
		if skipN < 0 {
			return false
		}
		buf = buf[skipN:]
	}
	return false
}
