// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: streamd_options.proto

package streamd_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProxyMode opts an RPC into protoc-gen-streamd-shim's autogen path.
//
// Setting `option (streamd.proxy) = AUTO;` on an RPC whose reply matches the
// shape `{ string Error; <=1 scalar field; }` instructs the plugin to emit the
// server proxy and client wrapper for that RPC, eliminating the per-RPC
// boilerplate fan-out across pkg/streamd/server and pkg/streamd/client.
type ProxyMode int32

const (
	ProxyMode_PROXY_MODE_UNSPECIFIED ProxyMode = 0
	ProxyMode_AUTO                   ProxyMode = 1
)

// Enum value maps for ProxyMode.
var (
	ProxyMode_name = map[int32]string{
		0: "PROXY_MODE_UNSPECIFIED",
		1: "AUTO",
	}
	ProxyMode_value = map[string]int32{
		"PROXY_MODE_UNSPECIFIED": 0,
		"AUTO":                   1,
	}
)

func (x ProxyMode) Enum() *ProxyMode {
	p := new(ProxyMode)
	*p = x
	return p
}

func (x ProxyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_options_proto_enumTypes[0].Descriptor()
}

func (ProxyMode) Type() protoreflect.EnumType {
	return &file_streamd_options_proto_enumTypes[0]
}

func (x ProxyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyMode.Descriptor instead.
func (ProxyMode) EnumDescriptor() ([]byte, []int) {
	return file_streamd_options_proto_rawDescGZIP(), []int{0}
}

var file_streamd_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ProxyMode)(nil),
		Field:         60001,
		Name:          "streamd.proxy",
		Tag:           "varint,60001,opt,name=proxy,enum=streamd.ProxyMode",
		Filename:      "streamd_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// 60001 is in the user-defined extension range (50000-99999) reserved by
	// google.protobuf for non-published, project-local extensions.
	//
	// optional streamd.ProxyMode proxy = 60001;
	E_Proxy = &file_streamd_options_proto_extTypes[0]
)

var File_streamd_options_proto protoreflect.FileDescriptor

const file_streamd_options_proto_rawDesc = "" +
	"\n" +
	"\x15streamd_options.proto\x12\astreamd\x1a google/protobuf/descriptor.proto*1\n" +
	"\tProxyMode\x12\x1a\n" +
	"\x16PROXY_MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AUTO\x10\x01:M\n" +
	"\x05proxy\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x01(\x0e2\x12.streamd.ProxyModeR\x05proxy\x88\x01\x01B\x11Z\x0fgo/streamd_grpcb\x06proto3"

var (
	file_streamd_options_proto_rawDescOnce sync.Once
	file_streamd_options_proto_rawDescData []byte
)

func file_streamd_options_proto_rawDescGZIP() []byte {
	file_streamd_options_proto_rawDescOnce.Do(func() {
		file_streamd_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamd_options_proto_rawDesc), len(file_streamd_options_proto_rawDesc)))
	})
	return file_streamd_options_proto_rawDescData
}

var file_streamd_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamd_options_proto_goTypes = []any{
	(ProxyMode)(0),                     // 0: streamd.ProxyMode
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_streamd_options_proto_depIdxs = []int32{
	1, // 0: streamd.proxy:extendee -> google.protobuf.MethodOptions
	0, // 1: streamd.proxy:type_name -> streamd.ProxyMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streamd_options_proto_init() }
func file_streamd_options_proto_init() {
	if File_streamd_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamd_options_proto_rawDesc), len(file_streamd_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_streamd_options_proto_goTypes,
		DependencyIndexes: file_streamd_options_proto_depIdxs,
		EnumInfos:         file_streamd_options_proto_enumTypes,
		ExtensionInfos:    file_streamd_options_proto_extTypes,
	}.Build()
	File_streamd_options_proto = out.File
	file_streamd_options_proto_goTypes = nil
	file_streamd_options_proto_depIdxs = nil
}
