// Code generated by protoc-gen-streamd-shim. DO NOT EDIT.
// source: streamd.proto

package streamd_grpc

import (
	context "context"
	errors "errors"
	fmt "fmt"
	xgrpc "github.com/xaionaro-go/xgrpc"
	io "io"
)

// ProxyClientBackend exposes the gRPC plumbing required by AUTO client
// wrappers. *streamd/client.Client satisfies this interface.
type ProxyClientBackend interface {
	GRPCClient(context.Context) (StreamDClient, io.Closer, error)
	ProcessError(ctx context.Context, err error) error
	GetCallWrapper() xgrpc.CallWrapperFunc
	GetRetryConfig() xgrpc.RetryConfig
}

// ProxyClient is the embeddable client-side counterpart of ProxyServer:
// it provides the AUTO RPC client methods, dispatching through Backend.
type ProxyClient struct {
	Backend ProxyClientBackend
}

// TranslatorReload is generated from option (streamd.proxy) = AUTO;
// on the streamd.StreamD/TranslatorReload RPC. Transport errors are
// wrapped with %w; in-band errors are surfaced as errors.New(reply.Error).
func (p *ProxyClient) TranslatorReload(ctx context.Context) (bool, error) {
	client, conn, err := p.Backend.GRPCClient(ctx)
	if err != nil {
		return false, err
	}
	defer conn.Close()
	reply, err := xgrpc.CallRetryable(ctx, p.Backend, client.TranslatorReload, &TranslatorReloadRequest{})
	if err != nil {
		return false, fmt.Errorf("unable to call TranslatorReload: %w", err)
	}
	if msg := reply.GetError(); msg != "" {
		return reply.GetApplied(), errors.New(msg)
	}
	return reply.GetApplied(), nil
}
