// Code generated by protoc-gen-streamd-shim. DO NOT EDIT.
// source: streamd.proto

package streamd_grpc

import (
	context "context"
)

// ProxyServerBackend is the subset of api.StreamD methods consumed by
// the AUTO server proxy. Only methods backing AUTO RPCs are listed.
type ProxyServerBackend interface {
	TranslatorReload(ctx context.Context) (bool, error)
}

// ProxyServer implements the AUTO subset of StreamDServer by delegating
// to a ProxyServerBackend. Embed it in a concrete server type to inherit
// the AUTO RPC handlers.
type ProxyServer struct {
	UnimplementedStreamDServer
	Backend ProxyServerBackend
}

// TranslatorReload is generated from option (streamd.proxy) = AUTO; on the
// streamd.StreamD/TranslatorReload RPC. The in-band error string is folded
// onto the reply (Error field); the gRPC error channel is reserved for
// transport-layer failures.
func (s *ProxyServer) TranslatorReload(
	ctx context.Context,
	req *TranslatorReloadRequest,
) (*TranslatorReloadReply, error) {
	val, err := s.Backend.TranslatorReload(ctx)
	reply := &TranslatorReloadReply{Applied: val}
	if err != nil {
		reply.Error = err.Error()
	}
	return reply, nil
}
