// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: translator.proto

package translator_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Translator_Translate_FullMethodName             = "/translator.Translator/Translate"
	Translator_Reconfigure_FullMethodName           = "/translator.Translator/Reconfigure"
	Translator_Stats_FullMethodName                 = "/translator.Translator/Stats"
	Translator_Ping_FullMethodName                  = "/translator.Translator/Ping"
	Translator_ClearHistory_FullMethodName          = "/translator.Translator/ClearHistory"
	Translator_TranslateViaProvider_FullMethodName  = "/translator.Translator/TranslateViaProvider"
	Translator_CompileTranslate_FullMethodName      = "/translator.Translator/CompileTranslate"
	Translator_CompileLanguageDetect_FullMethodName = "/translator.Translator/CompileLanguageDetect"
)

// TranslatorClient is the client API for Translator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Translator is the RPC interface streamd uses to call into a translator
// subprocess. The subprocess owns the in-flight TranslatorChain and applies
// configuration via Reconfigure; streamd retains no chain state of its own.
//
// Error semantics (uniform across every RPC on this service):
//   - Application-level failures (no chain loaded yet, parse/build failure,
//     provider-not-found, per-call provider error, payload rejected, etc.)
//     are surfaced on the reply's in-band `error` field. The handler returns
//     (reply, nil) so the gRPC status stays OK. Callers MUST always inspect
//     reply.error even when the gRPC error is nil.
//   - The gRPC error channel is reserved for transport-layer failures the
//     caller cannot recover from at the application layer: network drops,
//     codec errors, deadline exceeded, server panic. A non-nil gRPC error
//     therefore means "the call did not complete on the server", never
//     "the call completed but the request was rejected".
//
// Replies carry partial telemetry (e.g. latencyNanos) on per-call failures
// so the caller can log timing for the failed attempt.
type TranslatorClient interface {
	// Translate forwards one chat message to the chain. The reply carries the
	// translated text plus metadata describing the outcome so streamd can keep
	// its observability counters in lock-step with the subprocess.
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error)
	// Reconfigure swaps the active chain configuration. The subprocess MUST
	// retain the old chain on error so in-flight calls and future Translate
	// requests keep working until streamd retries with a fixed config.
	Reconfigure(ctx context.Context, in *ReconfigureRequest, opts ...grpc.CallOption) (*ReconfigureReply, error)
	// Stats returns a snapshot of the chain-level and per-provider counters.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error)
	// Ping is the liveness probe. The subprocess answers immediately so the
	// streamd-side supervisor can distinguish a hung subprocess from a slow
	// translation.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// ClearHistory drops every recorded ChatHistoryEntry on the active chain.
	// Returns the count of dropped entries. No-op (DroppedEntries=0) when no
	// chain is loaded.
	ClearHistory(ctx context.Context, in *ClearHistoryRequest, opts ...grpc.CallOption) (*ClearHistoryReply, error)
	// TranslateViaProvider bypasses the chain's detector + spelling-fallback
	// pipeline and calls one specific provider's Translate directly. Used by
	// ad-hoc replay tooling to compare a single provider's behaviour without
	// the chain's outcome decisioning. The reply has no Outcome enum because
	// there is no chain disposition to report — only success or error.
	TranslateViaProvider(ctx context.Context, in *TranslateViaProviderRequest, opts ...grpc.CallOption) (*TranslateViaProviderReply, error)
	// CompileTranslate renders the system + user prompts the chain WOULD
	// emit for a translation step, without calling any provider. Used by
	// ad-hoc debug tooling that needs to inspect / pipe the prompts (e.g.
	// to curl/jq) without burning a real Translate call. The reply's
	// history_snapshot is the rendered string returned by the chain's
	// formatHistory at RPC arrival time (uses historyMu); consecutive calls
	// may differ as the chain progresses. Errors follow the in-band rule
	// documented at the top of this service.
	CompileTranslate(ctx context.Context, in *CompileTranslateRequest, opts ...grpc.CallOption) (*CompileTranslateReply, error)
	// CompileLanguageDetect renders the system + user prompts the chain
	// WOULD emit for the language-detection step, without calling any
	// provider. The reply's history_snapshot is the rendered string from
	// formatHistory at RPC arrival time (uses historyMu); consecutive
	// calls may differ as the chain progresses. The system prompt uses
	// the deliberately asymmetric "Recent chat:" label (translate uses
	// "Recent chat for context:") — observable on the wire. Errors follow
	// the in-band rule documented at the top of this service.
	CompileLanguageDetect(ctx context.Context, in *CompileLanguageDetectRequest, opts ...grpc.CallOption) (*CompileLanguageDetectReply, error)
}

type translatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslatorClient(cc grpc.ClientConnInterface) TranslatorClient {
	return &translatorClient{cc}
}

func (c *translatorClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateReply)
	err := c.cc.Invoke(ctx, Translator_Translate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) Reconfigure(ctx context.Context, in *ReconfigureRequest, opts ...grpc.CallOption) (*ReconfigureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconfigureReply)
	err := c.cc.Invoke(ctx, Translator_Reconfigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsReply)
	err := c.cc.Invoke(ctx, Translator_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, Translator_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) ClearHistory(ctx context.Context, in *ClearHistoryRequest, opts ...grpc.CallOption) (*ClearHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearHistoryReply)
	err := c.cc.Invoke(ctx, Translator_ClearHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) TranslateViaProvider(ctx context.Context, in *TranslateViaProviderRequest, opts ...grpc.CallOption) (*TranslateViaProviderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateViaProviderReply)
	err := c.cc.Invoke(ctx, Translator_TranslateViaProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) CompileTranslate(ctx context.Context, in *CompileTranslateRequest, opts ...grpc.CallOption) (*CompileTranslateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileTranslateReply)
	err := c.cc.Invoke(ctx, Translator_CompileTranslate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translatorClient) CompileLanguageDetect(ctx context.Context, in *CompileLanguageDetectRequest, opts ...grpc.CallOption) (*CompileLanguageDetectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileLanguageDetectReply)
	err := c.cc.Invoke(ctx, Translator_CompileLanguageDetect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslatorServer is the server API for Translator service.
// All implementations must embed UnimplementedTranslatorServer
// for forward compatibility.
//
// Translator is the RPC interface streamd uses to call into a translator
// subprocess. The subprocess owns the in-flight TranslatorChain and applies
// configuration via Reconfigure; streamd retains no chain state of its own.
//
// Error semantics (uniform across every RPC on this service):
//   - Application-level failures (no chain loaded yet, parse/build failure,
//     provider-not-found, per-call provider error, payload rejected, etc.)
//     are surfaced on the reply's in-band `error` field. The handler returns
//     (reply, nil) so the gRPC status stays OK. Callers MUST always inspect
//     reply.error even when the gRPC error is nil.
//   - The gRPC error channel is reserved for transport-layer failures the
//     caller cannot recover from at the application layer: network drops,
//     codec errors, deadline exceeded, server panic. A non-nil gRPC error
//     therefore means "the call did not complete on the server", never
//     "the call completed but the request was rejected".
//
// Replies carry partial telemetry (e.g. latencyNanos) on per-call failures
// so the caller can log timing for the failed attempt.
type TranslatorServer interface {
	// Translate forwards one chat message to the chain. The reply carries the
	// translated text plus metadata describing the outcome so streamd can keep
	// its observability counters in lock-step with the subprocess.
	Translate(context.Context, *TranslateRequest) (*TranslateReply, error)
	// Reconfigure swaps the active chain configuration. The subprocess MUST
	// retain the old chain on error so in-flight calls and future Translate
	// requests keep working until streamd retries with a fixed config.
	Reconfigure(context.Context, *ReconfigureRequest) (*ReconfigureReply, error)
	// Stats returns a snapshot of the chain-level and per-provider counters.
	Stats(context.Context, *StatsRequest) (*StatsReply, error)
	// Ping is the liveness probe. The subprocess answers immediately so the
	// streamd-side supervisor can distinguish a hung subprocess from a slow
	// translation.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// ClearHistory drops every recorded ChatHistoryEntry on the active chain.
	// Returns the count of dropped entries. No-op (DroppedEntries=0) when no
	// chain is loaded.
	ClearHistory(context.Context, *ClearHistoryRequest) (*ClearHistoryReply, error)
	// TranslateViaProvider bypasses the chain's detector + spelling-fallback
	// pipeline and calls one specific provider's Translate directly. Used by
	// ad-hoc replay tooling to compare a single provider's behaviour without
	// the chain's outcome decisioning. The reply has no Outcome enum because
	// there is no chain disposition to report — only success or error.
	TranslateViaProvider(context.Context, *TranslateViaProviderRequest) (*TranslateViaProviderReply, error)
	// CompileTranslate renders the system + user prompts the chain WOULD
	// emit for a translation step, without calling any provider. Used by
	// ad-hoc debug tooling that needs to inspect / pipe the prompts (e.g.
	// to curl/jq) without burning a real Translate call. The reply's
	// history_snapshot is the rendered string returned by the chain's
	// formatHistory at RPC arrival time (uses historyMu); consecutive calls
	// may differ as the chain progresses. Errors follow the in-band rule
	// documented at the top of this service.
	CompileTranslate(context.Context, *CompileTranslateRequest) (*CompileTranslateReply, error)
	// CompileLanguageDetect renders the system + user prompts the chain
	// WOULD emit for the language-detection step, without calling any
	// provider. The reply's history_snapshot is the rendered string from
	// formatHistory at RPC arrival time (uses historyMu); consecutive
	// calls may differ as the chain progresses. The system prompt uses
	// the deliberately asymmetric "Recent chat:" label (translate uses
	// "Recent chat for context:") — observable on the wire. Errors follow
	// the in-band rule documented at the top of this service.
	CompileLanguageDetect(context.Context, *CompileLanguageDetectRequest) (*CompileLanguageDetectReply, error)
	mustEmbedUnimplementedTranslatorServer()
}

// UnimplementedTranslatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslatorServer struct{}

func (UnimplementedTranslatorServer) Translate(context.Context, *TranslateRequest) (*TranslateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedTranslatorServer) Reconfigure(context.Context, *ReconfigureRequest) (*ReconfigureReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconfigure not implemented")
}
func (UnimplementedTranslatorServer) Stats(context.Context, *StatsRequest) (*StatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedTranslatorServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTranslatorServer) ClearHistory(context.Context, *ClearHistoryRequest) (*ClearHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearHistory not implemented")
}
func (UnimplementedTranslatorServer) TranslateViaProvider(context.Context, *TranslateViaProviderRequest) (*TranslateViaProviderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TranslateViaProvider not implemented")
}
func (UnimplementedTranslatorServer) CompileTranslate(context.Context, *CompileTranslateRequest) (*CompileTranslateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompileTranslate not implemented")
}
func (UnimplementedTranslatorServer) CompileLanguageDetect(context.Context, *CompileLanguageDetectRequest) (*CompileLanguageDetectReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompileLanguageDetect not implemented")
}
func (UnimplementedTranslatorServer) mustEmbedUnimplementedTranslatorServer() {}
func (UnimplementedTranslatorServer) testEmbeddedByValue()                    {}

// UnsafeTranslatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslatorServer will
// result in compilation errors.
type UnsafeTranslatorServer interface {
	mustEmbedUnimplementedTranslatorServer()
}

func RegisterTranslatorServer(s grpc.ServiceRegistrar, srv TranslatorServer) {
	// If the following call panics, it indicates UnimplementedTranslatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Translator_ServiceDesc, srv)
}

func _Translator_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_Translate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_Reconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).Reconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_Reconfigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).Reconfigure(ctx, req.(*ReconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_ClearHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).ClearHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_ClearHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).ClearHistory(ctx, req.(*ClearHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_TranslateViaProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateViaProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).TranslateViaProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_TranslateViaProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).TranslateViaProvider(ctx, req.(*TranslateViaProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_CompileTranslate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileTranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).CompileTranslate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_CompileTranslate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).CompileTranslate(ctx, req.(*CompileTranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translator_CompileLanguageDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileLanguageDetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServer).CompileLanguageDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translator_CompileLanguageDetect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServer).CompileLanguageDetect(ctx, req.(*CompileLanguageDetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Translator_ServiceDesc is the grpc.ServiceDesc for Translator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Translator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translator.Translator",
	HandlerType: (*TranslatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Translate",
			Handler:    _Translator_Translate_Handler,
		},
		{
			MethodName: "Reconfigure",
			Handler:    _Translator_Reconfigure_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Translator_Stats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Translator_Ping_Handler,
		},
		{
			MethodName: "ClearHistory",
			Handler:    _Translator_ClearHistory_Handler,
		},
		{
			MethodName: "TranslateViaProvider",
			Handler:    _Translator_TranslateViaProvider_Handler,
		},
		{
			MethodName: "CompileTranslate",
			Handler:    _Translator_CompileTranslate_Handler,
		},
		{
			MethodName: "CompileLanguageDetect",
			Handler:    _Translator_CompileLanguageDetect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "translator.proto",
}
